/*
 * Copyright (c) 2009-2017 CNRS/LAAS
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/**
 ** Author: Matthieu Herrb
 ** Date: April 2009 for rmp400, updated for rmp440, May 2013,
 **       updated for genom3, January 2017
 **
 **/

#pragma require "openrobots-idl >= 1.1"

#include <or/time/time.idl>

/* internal structure for communication with RMP440 */
native rmp440_io;
native rmp440_feedback;
native FE_STR;
native GYRO_DATA;
native MTI_DATA;

module rmp440 {

  const double sec_period = 0.05; // 50ms -- MCU RTT is ~30ms

  const double delay_gyro_omega = 0.3; // delay between command and measure, in seconds
  const double kp_gyro_omega = 2.0;
  const double kp_gyro_theta = 10.0;
  const double ki_gyro_theta = 2.0;

  // joystick
  const double joystick_vgain = 1./(32768.0*32768.0); /* 1 m/s max */
  const double joystick_wgain = 1./(32768.0*32768.0); /* 1 rad/s max */

  enum mode {
    mode_idle,
    mode_motors_off,
    mode_manual,
    mode_track,
    mode_emergency,
    mode_power_coord
  };

/* copy-paste of rmp440.h:rmp440_feedback */
  struct feedback_genom {
    or::time::ts timestamp;
    unsigned long fault_status[4];
    unsigned long mcu_fault_status[4];
    float frame_count;
    unsigned long operational_state;
    unsigned long dynamic_response;
    float min_propulsion_batt_soc; /* min. of all batt. state of charge */
    float aux_batt_soc;	       /* aux batt. state of charge */
    float inertial_x_acc;
    float inertial_y_acc;
    float inertial_x_rate;
    float inertial_y_rate;
    float inertial_z_rate;
    float pse_pitch;
    float pse_pitch_rate;
    float pse_roll;
    float pse_roll_rate;
    float pse_yaw_rate;
    unsigned long pse_data_is_valid;
    float yaw_rate_limit;
    float vel_limit;
    float linear_accel;
    float linear_vel;
    float differential_wheel_vel;
    float right_front_vel;
    float left_front_vel;
    float right_rear_vel;
    float left_rear_vel;
    float right_front_pos;
    float left_front_pos;
    float right_rear_pos;
    float left_rear_pos;
    float linear_pos;
    float right_front_current;
    float left_front_current;
    float right_rear_current;
    float left_rear_current;
    float max_motor_current;
    float right_front_current_limit;
    float left_front_current_limit;
    float right_rear_current_limit;
    float left_rear_current_limit;
    float min_motor_current_limit;
    float front_base_batt_1_soc;
    float front_base_batt_2_soc;
    float rear_base_batt_1_soc;
    float rear_base_batt_2_soc;
    float front_base_batt_1_temp;
    float front_base_batt_2_temp;
    float rear_base_batt_1_temp;
    float rear_base_batt_2_temp;
    float vel_target;
    float yaw_rate_target;
    float angle_target;	/* only used on omni platforms */
    float aux_batt_voltage;
    float aux_batt_current;
    float aux_batt_temp;
    unsigned long abb_system_status;
    unsigned long abb_batt_status;
    unsigned long aux_batt_faults;
    float ccu_7p2_battery_voltage;
    unsigned long sp_sw_build_id;
    unsigned long uip_sw_build_id;
    float mcu_inst_power[4];
    float mcu_total_energy[4];
    float fram_vel_limit;
    float fram_accel_limit;
    float fram_decel_limit;
    float fram_dtz_decel_limit;
    float fram_coastdown_decel;
    float fram_yaw_rate_limit;
    float fram_yaw_accel_limit;
    float fram_tire_diameter;
    float fram_wheel_base_length;
    float fram_wheel_track_width;
    float fram_transmission_ratio;
    unsigned long fram_config_bitmap;
    unsigned long fram_eth_ip_address;
    unsigned short fram_eth_port_number;
    unsigned long fram_eth_subnet_mask;
    unsigned long fram_eth_gateway;
    unsigned long user_feedback_bitmap[4];
  };

  struct status_str {
    mode rs_mode;
    feedback_genom rs_data;
  };

  /* Kinematics of the robot */
  struct kinematics_str {
    double leftWheelRadius;
    double rightWheelRadius;
    double axisWidth;
  };

  /* Current dynamic parameters, from the nvram */
  struct dynamic_str {
    double vMax;
    double wMax;
    double linAccelMax;
    double angAccelMax;
  };

  /* Coefficient proportionnel a la vitesse pour calculer l'erreur sur
     le deplacement des roues */
  struct var_params {
    double coeffLin;
    double coeffAng;
    double coeffLinAng;
  };

  /* Gyro */
  enum gyro_mode {
    gyro_off,
    gyro_on_if_motion,
    gyro_on
  };

  struct gyro_params {
    gyro_mode mode;
    string port;
    GYRO_TYPE type;
    double latitude;
    double woffset;
  };

  struct gyro {
    boolean gyroOn;
    gyro_mode currentMode;
    double gyroToRobotOffset;
    double gyroTheta;
    double robotTheta;
    double gyroOmega;
  };

  struct gyro_asserv {
    boolean enabled; // is asserv enabled
    boolean first; // first call to this function ?
    boolean straight; // is in straight mode ?
    double straight_angle; // angle for straight mode
    double prev_reference;
    double prev_measure;
    double prev_command;
    double prev_t;
    double integral_s;
    double jump_t; // last jump time
  };

  /* MTI */
  enum mti_mode {
    mti_off,
    mti_on_if_motion,
    mti_on
  };

  struct mti_params {
    mti_mode mode;
    string port;
    long outputMode;
    long outputFormat;
  };

  struct mti_inertial_data {
    float acc[3];
    float gyr[3];
    float mag[3];
    float euler[3];
    long count;
    double timeStampRaw;
    double timeStampUndelayed;
    double timeStampFiltered;
  };
  
  struct mti {
    boolean mtiOn;
    mti_mode currentMode;
    mti_inertial_data data;
  };

  /* Acceleration limitation code */
  struct max_accel {
    double prev_vel_command;
    double prev_vel_command_t;
  };

};

/* begin COMMON between RMP models */
module rmp {
  enum model {
    model_400,
    model_440
  };

  struct status_str {
    double receive_date;
    model robot_model;
    rmp440::mode rs_mode;
    double propulsion_battery_level;
    double aux_battery_level;
    double pitch, roll, yaw_rate;
    double v, w;
    double v_target, w_target;
    float right_front_vel, left_front_vel, right_rear_vel, left_rear_vel;
    float right_front_pos, left_front_pos, right_rear_pos, left_rear_pos;
    float right_front_torque, left_front_torque, right_rear_torque, left_rear_torque;
  };
};
/* end COMMON between RMP models */
